### ISSUE TITLE
How to decrease keybyte 

### ISSUE THREAD

**Issue by hichay** [ganlvtech/lua-simple-encrypt#6]
Im trying to decrease keybyte to make file smaller. it too big for running.

**Comment by ganlvtech** [comment]
This encryption is really simple. It just do simple XOR and shuffling. The encrpytion is extremely inefficienct. The encrpyted file may cost hundreds times space as the original file, because there is a huge shuffle map.

The shuffle map contains the position of each byte and is written in decimal. So the file size may `O(nlogn)`, where `n` is the size of original file size. Increase key length won't increase encrypted file size. And decrease won't either.

I'm really sorry that this tool are not friendly with bigger file. If you really need a more efficient encrypt method, please try to find some other tools.

Thanks.

**Comment by ganlvtech** [comment]
You can try to remove the shuffle part. The file size with decrease significantly. It may require some more work. Welcome for sending a PR.
